from __future__ import annotations

import asyncio
import os
import shutil
import tempfile
import threading
import time
import uuid
from pathlib import Path
from typing import Any

import fitz  # PyMuPDF
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, Response
from pdf2docx import Converter
from pydantic import BaseModel, Field

APP_DIR = Path(__file__).resolve().parent
INDEX_HTML = APP_DIR / "index.html"

# All working files live below the OS temp directory.
WORK_ROOT = Path(tempfile.gettempdir()) / "pdf_workbench"
UPLOAD_DIR = WORK_ROOT / "uploads"
OUTPUT_DIR = WORK_ROOT / "outputs"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

MAX_UPLOAD_MB = 500
MAX_UPLOAD_BYTES = MAX_UPLOAD_MB * 1024 * 1024
TEMP_MAX_AGE_SECONDS = 2 * 60 * 60

app = FastAPI(title="PDF Workbench", version="1.0.0")

# The application is intended to be local-only. CORS is permissive enough for
# pywebview's local page and normal browser development, but the server binds
# only to 127.0.0.1 when launched by desktop.py.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

_cleanup_stop = threading.Event()


class PageRef(BaseModel):
    doc_id: str = Field(min_length=1, max_length=100)
    page_index: int = Field(ge=0)


class PagesRequest(BaseModel):
    pages: list[PageRef] = Field(min_length=1)


class NativeUploadRequest(BaseModel):
    paths: list[str] = Field(min_length=1, max_length=50)


class ExportRequest(BaseModel):
    pages: list[PageRef] = Field(min_length=1)
    output_path: str | None = None
    filename: str = "merged.pdf"


def _safe_doc_path(doc_id: str) -> Path:
    # doc_id is generated by this application, but still validate defensively.
    if not doc_id or any(c not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_" for c in doc_id):
        raise HTTPException(status_code=400, detail="Invalid document ID")
    path = UPLOAD_DIR / f"{doc_id}.pdf"
    if not path.is_file():
        raise HTTPException(status_code=404, detail="Document not found")
    return path


def _validate_page_refs(pages: list[PageRef]) -> list[tuple[Path, int]]:
    validated: list[tuple[Path, int]] = []
    for ref in pages:
        path = _safe_doc_path(ref.doc_id)
        try:
            with fitz.open(path) as doc:
                page_count = doc.page_count
        except Exception as exc:
            raise HTTPException(
                status_code=400, detail=f"Cannot open PDF: {path.name}") from exc

        if ref.page_index >= page_count:
            raise HTTPException(
                status_code=400,
                detail=f"Page {ref.page_index + 1} does not exist in {path.name}",
            )
        validated.append((path, ref.page_index))
    return validated


def _copy_selected_pages(pages: list[PageRef], output_path: Path) -> None:
    validated = _validate_page_refs(pages)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    result = fitz.open()
    try:
        # Opening source documents one-by-one keeps memory usage predictable.
        opened: dict[Path, fitz.Document] = {}
        try:
            for path, page_index in validated:
                src = opened.setdefault(path, fitz.open(path))
                result.insert_pdf(src, from_page=page_index,
                                  to_page=page_index)
        finally:
            for doc in opened.values():
                doc.close()

        result.save(output_path, garbage=4, deflate=True)
    finally:
        result.close()


def _cleanup_worker() -> None:
    while not _cleanup_stop.wait(15 * 60):
        cutoff = time.time() - TEMP_MAX_AGE_SECONDS
        for folder in (UPLOAD_DIR, OUTPUT_DIR):
            for item in folder.iterdir():
                try:
                    if item.stat().st_mtime < cutoff:
                        if item.is_dir():
                            shutil.rmtree(item, ignore_errors=True)
                        else:
                            item.unlink(missing_ok=True)
                except OSError:
                    pass


@app.on_event("startup")
async def startup_event() -> None:
    threading.Thread(target=_cleanup_worker, daemon=True,
                     name="pdf-workbench-cleanup").start()


@app.on_event("shutdown")
async def shutdown_event() -> None:
    _cleanup_stop.set()


@app.get("/", response_class=HTMLResponse)
async def index() -> HTMLResponse:
    if not INDEX_HTML.is_file():
        raise HTTPException(status_code=500, detail="index.html is missing")
    return HTMLResponse(INDEX_HTML.read_text(encoding="utf-8"))


@app.get("/health")
async def health() -> dict[str, Any]:
    return {"ok": True, "app": "PDF Workbench", "version": "1.0.0"}


async def _store_upload(upload: UploadFile) -> dict[str, Any]:
    original_name = Path(upload.filename or "document.pdf").name
    if not original_name.lower().endswith(".pdf"):
        raise HTTPException(
            status_code=400, detail=f"{original_name}: only PDF files are supported")

    doc_id = uuid.uuid4().hex
    destination = UPLOAD_DIR / f"{doc_id}.pdf"

    total = 0
    try:
        with destination.open("wb") as out:
            while True:
                chunk = await upload.read(1024 * 1024)
                if not chunk:
                    break
                total += len(chunk)
                if total > MAX_UPLOAD_BYTES:
                    raise HTTPException(
                        status_code=413,
                        detail=f"{original_name}: file exceeds {MAX_UPLOAD_MB} MB limit",
                    )
                out.write(chunk)

        with fitz.open(destination) as doc:
            page_count = doc.page_count
            if page_count == 0:
                raise ValueError("PDF has no pages")
    except HTTPException:
        destination.unlink(missing_ok=True)
        raise
    except Exception as exc:
        destination.unlink(missing_ok=True)
        raise HTTPException(
            status_code=400, detail=f"Invalid PDF: {original_name}") from exc
    finally:
        await upload.close()

    return {
        "doc_id": doc_id,
        "name": original_name,
        "size": total,
        "page_count": page_count,
        "pages": [
            {"doc_id": doc_id, "page_index": i,
                "label": f"{original_name} · Page {i + 1}"}
            for i in range(page_count)
        ],
    }


@app.post("/api/upload")
async def upload(files: list[UploadFile] = File(...)) -> dict[str, Any]:
    if not files:
        raise HTTPException(status_code=400, detail="No files supplied")
    if len(files) > 50:
        raise HTTPException(
            status_code=400, detail="Maximum 50 PDFs per batch")

    documents = []
    for item in files:
        documents.append(await _store_upload(item))
    return {"documents": documents}


@app.post("/api/upload-paths")
async def upload_paths(payload: NativeUploadRequest) -> dict[str, Any]:
    """Import files selected by the native pywebview file dialog.

    This is deliberately restricted to PDF files and reads them locally.
    """
    documents = []
    for raw_path in payload.paths:
        source = Path(raw_path).expanduser().resolve()
        if source.suffix.lower() != ".pdf":
            raise HTTPException(
                status_code=400, detail=f"{source.name}: only PDF files are supported")
        if not source.is_file():
            raise HTTPException(
                status_code=400, detail=f"File not found: {source.name}")
        if source.stat().st_size > MAX_UPLOAD_BYTES:
            raise HTTPException(
                status_code=413, detail=f"{source.name}: file exceeds {MAX_UPLOAD_MB} MB")

        doc_id = uuid.uuid4().hex
        destination = UPLOAD_DIR / f"{doc_id}.pdf"
        try:
            shutil.copy2(source, destination)
            with fitz.open(destination) as doc:
                page_count = doc.page_count
        except Exception as exc:
            destination.unlink(missing_ok=True)
            raise HTTPException(
                status_code=400, detail=f"Invalid PDF: {source.name}") from exc

        documents.append(
            {
                "doc_id": doc_id,
                "name": source.name,
                "size": source.stat().st_size,
                "page_count": page_count,
                "pages": [
                    {"doc_id": doc_id, "page_index": i,
                        "label": f"{source.name} · Page {i + 1}"}
                    for i in range(page_count)
                ],
            }
        )

    return {"documents": documents}


@app.get("/api/page-image/{doc_id}/{page_index}")
async def page_image(doc_id: str, page_index: int) -> Response:
    path = _safe_doc_path(doc_id)
    try:
        with fitz.open(path) as doc:
            if page_index < 0 or page_index >= doc.page_count:
                raise HTTPException(status_code=404, detail="Page not found")
            page = doc.load_page(page_index)

            # 1.35x gives useful thumbnails while remaining fast.
            pix = page.get_pixmap(matrix=fitz.Matrix(1.35, 1.35), alpha=False)
            png = pix.tobytes("png")
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(
            status_code=400, detail="Could not render page") from exc

    return Response(
        content=png,
        media_type="image/png",
        headers={"Cache-Control": "public, max-age=3600"},
    )


@app.post("/api/merge")
async def merge(payload: ExportRequest):
    filename = Path(payload.filename).name or "merged.pdf"
    if not filename.lower().endswith(".pdf"):
        filename += ".pdf"

    if payload.output_path:
        target = Path(payload.output_path).expanduser().resolve()
        # Native save dialogs are the intended way to supply output_path.
        # Refuse obviously unsafe special paths.
        if target.is_dir():
            raise HTTPException(
                status_code=400, detail="Output path must be a file")
    else:
        target = OUTPUT_DIR / f"{uuid.uuid4().hex}_{filename}"

    try:
        _copy_selected_pages(payload.pages, target)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(
            status_code=500, detail=f"Merge failed: {exc}") from exc

    if payload.output_path:
        return JSONResponse({"ok": True, "path": str(target), "filename": filename})

    return FileResponse(
        target,
        media_type="application/pdf",
        filename=filename,
        headers={"X-PDF-Workbench-Path": str(target)},
    )


@app.post("/convert-to-word", response_model=None)
async def convert_to_word(payload: ExportRequest):
    filename = Path(payload.filename).name or "converted.docx"
    filename = Path(filename).with_suffix(".docx").name

    if payload.output_path:
        target = Path(payload.output_path).expanduser().resolve()
        if target.is_dir():
            raise HTTPException(
                status_code=400, detail="Output path must be a file")
    else:
        target = OUTPUT_DIR / f"{uuid.uuid4().hex}_{filename}"

    source_pdf = OUTPUT_DIR / f"{uuid.uuid4().hex}_conversion_source.pdf"

    try:
        _copy_selected_pages(payload.pages, source_pdf)
        converter = Converter(str(source_pdf))
        try:
            converter.convert(str(target), start=0, end=None)
        finally:
            converter.close()
    except HTTPException:
        raise
    except Exception as exc:
        target.unlink(missing_ok=True)
        raise HTTPException(
            status_code=500, detail=f"Word conversion failed: {exc}") from exc
    finally:
        source_pdf.unlink(missing_ok=True)

    if payload.output_path:
        return JSONResponse({"ok": True, "path": str(target), "filename": filename})

    return FileResponse(
        target,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        filename=filename,
        headers={"X-PDF-Workbench-Path": str(target)},
    )
